[package]
name = "snapfaas"
version = "0.1.0"
authors = ["David H. Liu<hl7@cs.princeton.edu>"]
edition = "2018"

[[bin]]
name = "snapctr"
path = "bins/snapctr/main.rs"

[lib]

[dependencies]
url = "2.1.0"
clap = "2.33.0"
log = "0.4"
simple_logger = "1.3.0"
serde = {version = "1.0.102", features = ["derive"]}
serde_yaml = "0.8.11"
shellexpand = "1.0.0"
