firerunner_path: "./target/release/firerunner"
kernel_path: "./resources/images/vmlinux-4.20.0"
runtimefs_dir: "./"
functions:
  - name: "build_tarball"
    runtimefs: "python3_build_tarball.ext4"
    vcpus: 1
    memory: 128 
    concurrency_limit: 600
