---
allow_network: false
firerunner_path: "./target/debug/firerunner"
kernel_path: "./resources/images/vmlinux-4.20.0"
runtimefs_dir: "./"
functions:
  build_tarball:
    network: false
    runtimefs: "list_tarball.ext4"
    vcpus: 1
    memory: 128 
    concurrency_limit: 600
