---
allow_network: false
firerunner_path: "./target/release/firerunner"
kernel_path: "./resources/images/vmlinux-4.20.0"
runtimefs_dir: "./"
functions:
  hello:
    runtimefs: "hello.ext4"
    vcpus: 1
    memory: 128
    concurrency_limit: 600
  build_tarball:
    runtimefs: "list_tarball.ext4"
    vcpus: 1
    memory: 128
    concurrency_limit: 600
