all: f1/output_f1.ext2 f2/output_f2.ext2 f3/output_f3.ext2

f1/output_f1.ext2: f1/workload.py
	make -C f1

f2/output_f2.ext2: f2/workload.py
	make -C f2

f3/output_f3.ext2: f3/workload.py
	make -C f3
